name: Test Projects
on: push
jobs:
  test:
    runs-on: ubunto-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
      - name: Install dependencies 
        run: npm ci
      - name: Run tests
        run: npm test